language: php

php: 5.6

before_install:
  - composer self-update

install:
  - composer install --no-dev --prefer-dist --optimize-autoloader

script:
  - echo ""

before_deploy:
  - zip -r authskautis conf images lang vendor action.php auth.php LICENSE plugin.info.txt README README.md

deploy:
  provider: releases
  api_key:
    secure: xO85fnfoPeGanFCIadtsREzmBT7XwQ1zVWlDniNAfce+syGxKeMkd/PgOAYtrnmcO1ResmJ4xvz0iynxLSuuTwyX0vAT+AMrRAR5gZvKmUt3yIALQJ46VcSO5rGXidIyojg0soeenlbNZI5VdFEBD6oiasQI3XhMwALRa+rrY6RU4THFMyglwVGpDExOkzuYQvNlzM6MaG5WNcDyrLT7KtZbp3zfXeBfTJf5hckZ0LgXjP03cMgGXg6o0y+vv7N4h26e7uykA92IoQNI0hga14dD873oQ4g3nEy4x7dAdH2YpsY2RNKIVRJVZMzl69jYNb5bh4c5gQ9CdQ/sk3yK2PJdT/BH/BHl+OuGDBX9m/o9Cvg4N8SRwhzLeoOyByCaGRmI30tftTEFlEtVQS6jmOxX8IOjRyNEWMlnB2O7cXlC2aN8y6r53LnxWUSXxdpHd9vAAA+N1G3MNgskZFF2kiKt8nbdY0RDYr24Yln00B44jCsGE12C+Ay2ieGe13Fr7ZcpZEOQsLWMENfRLQn9BBiOmOn6aMWHuyvS5UM384bPxbXzWY3/ky50hGJ87VkHfDl9iPf91MTSe4kPWZk3QAxodcoJ3V1KcXIdIqEKPVlD1rT5iVxW6op6rNKVGXaJqqkAfyIW135mhWvDsiPmTh/Dla1jniAtXcqOxtRsO+c=
  file: authskautis.zip
  skip_cleanup: true
  on:
    repo: skaut/skautis-dokuwiki
    branch: master
    tags: true
